version: '3.4'



services:
  selenium:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    network_mode: "host"
    shm_size: 2g
    privileged: true
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=3
  alibot:
    image: alibot
    build:
      context: .
      dockerfile: ./Dockerfile
  
